---
version: 2.1
jobs:
  building:
    machine: true
    steps:
      - checkout
      - run:
          name: "Install AWS-CLI"
          command: |
            sudo apt update
            sudo apt install -y awscli
      - run:
          name: "ECR Auth"
          command: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 737584674007.dkr.ecr.us-east-1.amazonaws.com
      - run:
          name: "building"
          command: |
            docker build -t 737584674007.dkr.ecr.us-east-1.amazonaws.com/my-ecr:${CIRCLE_SHA1:0:8} .
            docker push 737584674007.dkr.ecr.us-east-1.amazonaws.com/my-ecr:${CIRCLE_SHA1:0:8}

workflows:
  say-hello-workflow:
    jobs:
      - building
