---
version: 2.1
jobs:
  building:
    docker:
      - image: arogudl/readytodeploy:latest
    steps:
      - checkout
      - run:
          name: aws
          command: aws --version
      - run:
          name: k8s
          command: kubectl version --short
      - run:
          name: helm
          command: helm version
workflows:
  say-hello-workflow:
    jobs:
      - building
