---
version: 2.1
jobs:
  building:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: dependencies
          command: echo downloding dependencies
      - run:
          name: building
          command: echo building
      - run:
          name: pushing
          command: echo pushing image
  deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: releasing
          command: echo deploying app
workflows:
  say-hello-workflow:
    jobs:
      - building
      - deployment:
          requires:
            - building
